# Generated by Django 5.1.1 on 2024-10-03 13:38

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Individual',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=20)),
                ('last_name', models.CharField(max_length=20)),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('gender', models.CharField(choices=[('male', 'Male'), ('female', 'Female')], max_length=6)),
                ('specialization', models.CharField(blank=True, max_length=100, null=True)),
                ('national_id', models.CharField(max_length=14, unique=True, validators=[django.core.validators.RegexValidator(message='National ID must be exactly 14 digits.', regex='^\\d{14}$')])),
                ('account_type', models.CharField(choices=[('hiring', 'Hiring'), ('seeking', 'Seeking')], max_length=10)),
                ('phone_number', models.CharField(blank=True, max_length=11, null=True, validators=[django.core.validators.RegexValidator(message='This is not a valid Egyptian phone number.', regex='^01[0-2,5]{1}[0-9]{8}$')])),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
