# Generated by Django 5.1.1 on 2024-10-06 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('individual', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='individual',
            name='account_type',
            field=models.CharField(choices=[('client', 'Client'), ('seeking', 'Seeking')], max_length=10),
        ),
    ]
