# Generated by Django 5.1.1 on 2024-10-06 18:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('individual', '0002_alter_individual_account_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='individual',
            name='user',
        ),
    ]
