# Generated by Django 5.1.1 on 2024-10-06 22:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('individual', '0004_individual_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='individual',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='individual',
            name='last_name',
        ),
    ]
