# Generated by Django 5.1.1 on 2024-10-09 19:09

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('industry', models.CharField(blank=True, max_length=100, null=True)),
                ('registration_id', models.CharField(blank=True, max_length=14, null=True, unique=True)),
                ('registration_documents', models.FileField(blank=True, null=True, upload_to='registration_docs/')),
                ('phone_number', models.CharField(blank=True, max_length=11, null=True, validators=[django.core.validators.RegexValidator(message='This is not a valid Egyptian phone number.', regex='^01[0-2,5]{1}[0-9]{8}$')])),
                ('location', models.CharField(max_length=200)),
                ('client_base', models.BooleanField(default=False, help_text='Select if the company is client based or not .')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
