# Generated by Django 5.1.1 on 2024-10-05 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='company',
            name='logo',
        ),
        migrations.RemoveField(
            model_name='company',
            name='registration_document',
        ),
        migrations.AddField(
            model_name='company',
            name='registration_documents',
            field=models.FileField(blank=True, null=True, upload_to='registration_docs/'),
        ),
    ]
