# Generated by Django 5.1.1 on 2024-10-04 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0002_remove_company_logo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='company_logos'),
        ),
        migrations.AddField(
            model_name='company',
            name='registration_document',
            field=models.FileField(blank=True, null=True, upload_to='company_documents/'),
        ),
    ]
