# Generated by Django 5.1.1 on 2024-10-07 15:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0003_rename_company_type_company_client_base'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='company',
            name='company_name',
        ),
    ]
