# Generated by Django 5.1.1 on 2024-10-03 23:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('individual', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('industry', models.CharField(blank=True, max_length=100, null=True)),
                ('post_status', models.CharField(blank=True, choices=[('active', 'Active'), ('draft', 'Draft'), ('disabled', 'Disabled')], default='Active', max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('budget', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('deadline', models.DateField(blank=True, null=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='individual.individual')),
            ],
        ),
    ]
