# Generated by Django 5.1.1 on 2024-10-06 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0002_remove_project_author_remove_project_budget_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='budget',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='deadline',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='industry',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='post_status',
            field=models.CharField(blank=True, choices=[('active', 'Active'), ('draft', 'Draft'), ('disabled', 'Disabled')], default='Active', max_length=100, null=True),
        ),
    ]
