# Generated by Django 5.1.1 on 2024-10-10 14:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('individual', '0006_alter_individual_user'),
        ('project', '0003_project_budget_project_deadline_project_industry_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='author',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='individual.individual'),
        ),
    ]
