# Generated by Django 5.1.1 on 2024-10-03 15:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('company', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('industry', models.CharField(blank=True, max_length=100, null=True)),
                ('post_status', models.CharField(choices=[('active', 'Active'), ('draft', 'Draft'), ('disabled', 'Disabled')], default='Active', max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('location', models.CharField(max_length=200)),
                ('job_type', models.CharField(blank=True, choices=[('part_time', 'Part Time'), ('full_time', 'Full Time'), ('remote', 'Remote')], max_length=10, null=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='company.company')),
            ],
        ),
    ]
