# Generated by Django 5.1.1 on 2024-10-05 22:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0002_remove_job_author_remove_job_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='industry',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='job',
            name='job_type',
            field=models.CharField(blank=True, choices=[('part_time', 'Part Time'), ('full_time', 'Full Time'), ('remote', 'Remote')], max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='job',
            name='location',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='job',
            name='post_status',
            field=models.CharField(choices=[('active', 'Active'), ('draft', 'Draft'), ('disabled', 'Disabled')], default='Active', max_length=100),
        ),
    ]
